/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const LetterType = IDL.Variant({
  'noc' : IDL.Null,
  'paymentReceived' : IDL.Null,
  'closerLetter' : IDL.Null,
  'paymentReceipt' : IDL.Null,
});
export const Time = IDL.Int;
export const LetterRecord = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'loanAmount' : IDL.Text,
  'date' : IDL.Text,
  'createdAt' : Time,
  'letterType' : LetterType,
  'loanAccountNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  'createLetter' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, LetterType],
      [IDL.Nat],
      [],
    ),
  'deleteLetter' : IDL.Func([IDL.Nat], [], []),
  'getAllLetters' : IDL.Func([], [IDL.Vec(LetterRecord)], ['query']),
  'getLetter' : IDL.Func([IDL.Nat], [LetterRecord], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const LetterType = IDL.Variant({
    'noc' : IDL.Null,
    'paymentReceived' : IDL.Null,
    'closerLetter' : IDL.Null,
    'paymentReceipt' : IDL.Null,
  });
  const Time = IDL.Int;
  const LetterRecord = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'loanAmount' : IDL.Text,
    'date' : IDL.Text,
    'createdAt' : Time,
    'letterType' : LetterType,
    'loanAccountNumber' : IDL.Text,
  });
  
  return IDL.Service({
    'createLetter' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, LetterType],
        [IDL.Nat],
        [],
      ),
    'deleteLetter' : IDL.Func([IDL.Nat], [], []),
    'getAllLetters' : IDL.Func([], [IDL.Vec(LetterRecord)], ['query']),
    'getLetter' : IDL.Func([IDL.Nat], [LetterRecord], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };