/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface LetterRecord {
    id: bigint;
    customerName: string;
    loanAmount: string;
    date: string;
    createdAt: Time;
    letterType: LetterType;
    loanAccountNumber: string;
}
export enum LetterType {
    noc = "noc",
    paymentReceived = "paymentReceived",
    closerLetter = "closerLetter",
    paymentReceipt = "paymentReceipt"
}
export interface backendInterface {
    createLetter(customerName: string, loanAccountNumber: string, loanAmount: string, date: string, letterType: LetterType): Promise<bigint>;
    deleteLetter(id: bigint): Promise<void>;
    getAllLetters(): Promise<Array<LetterRecord>>;
    getLetter(id: bigint): Promise<LetterRecord>;
}
import type { LetterRecord as _LetterRecord, LetterType as _LetterType, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createLetter(arg0: string, arg1: string, arg2: string, arg3: string, arg4: LetterType): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createLetter(arg0, arg1, arg2, arg3, to_candid_LetterType_n1(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLetter(arg0, arg1, arg2, arg3, to_candid_LetterType_n1(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async deleteLetter(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLetter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLetter(arg0);
            return result;
        }
    }
    async getAllLetters(): Promise<Array<LetterRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLetters();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLetters();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLetter(arg0: bigint): Promise<LetterRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.getLetter(arg0);
                return from_candid_LetterRecord_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLetter(arg0);
            return from_candid_LetterRecord_n4(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_LetterRecord_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LetterRecord): LetterRecord {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_LetterType_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LetterType): LetterType {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    customerName: string;
    loanAmount: string;
    date: string;
    createdAt: _Time;
    letterType: _LetterType;
    loanAccountNumber: string;
}): {
    id: bigint;
    customerName: string;
    loanAmount: string;
    date: string;
    createdAt: Time;
    letterType: LetterType;
    loanAccountNumber: string;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        loanAmount: value.loanAmount,
        date: value.date,
        createdAt: value.createdAt,
        letterType: from_candid_LetterType_n6(_uploadFile, _downloadFile, value.letterType),
        loanAccountNumber: value.loanAccountNumber
    };
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    noc: null;
} | {
    paymentReceived: null;
} | {
    closerLetter: null;
} | {
    paymentReceipt: null;
}): LetterType {
    return "noc" in value ? LetterType.noc : "paymentReceived" in value ? LetterType.paymentReceived : "closerLetter" in value ? LetterType.closerLetter : "paymentReceipt" in value ? LetterType.paymentReceipt : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LetterRecord>): Array<LetterRecord> {
    return value.map((x)=>from_candid_LetterRecord_n4(_uploadFile, _downloadFile, x));
}
function to_candid_LetterType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LetterType): _LetterType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LetterType): {
    noc: null;
} | {
    paymentReceived: null;
} | {
    closerLetter: null;
} | {
    paymentReceipt: null;
} {
    return value == LetterType.noc ? {
        noc: null
    } : value == LetterType.paymentReceived ? {
        paymentReceived: null
    } : value == LetterType.closerLetter ? {
        closerLetter: null
    } : value == LetterType.paymentReceipt ? {
        paymentReceipt: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
